[tool.poetry]
name = "web-scraping"
version = "0.1.0"
description = ""
authors = ["Reema Eilouti <reema.eilouti@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
bs4 = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
